class V1NodeSystemInfo:
    @property
    def container_runtime_version(self) -> str: ...
    @property
    def kernel_version(self) -> str: ...
    @property
    def kubelet_version(self) -> str: ...
