from typing import Dict

from . import V1ObjectMeta, V1PersistentVolumeSpec, V1PersistentVolumeStatus

class V1PersistentVolume:
    def to_dict(self) -> Dict: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @property
    def spec(self) -> V1PersistentVolumeSpec: ...
    @property
    def status(self) -> V1PersistentVolumeStatus: ...
