from . import V1ContainerStatus, V1PodCondition

class V1PodStatus:
    @property
    def container_statuses(self) -> list[V1ContainerStatus]: ...
    @property
    def ephemeral_container_statuses(self) -> list[V1ContainerStatus]: ...
    @property
    def conditions(self) -> list[V1PodCondition]: ...
    @property
    def phase(self) -> str: ...
    @property
    def host_ip(self) -> str: ...
