from typing import Any, Optional

from .. import V1DeploymentList
from ..api_client import ApiClient

class AppsV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[ApiClient] = ...) -> None: ...
    def list_namespaced_deployment(self, namespace: str, **kwargs: Any) -> V1DeploymentList: ...
    def patch_namespaced_deployment_scale(self, name: str, namespace: str, body: object) -> None: ...
