from typing import Any, Optional

from .. import V1APIResourceList, V1CronJobList, V1Job, V1JobList
from ..api_client import ApiClient

class BatchV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[ApiClient] = ...) -> None: ...
    def list_namespaced_job(self, namespace: str, **kwargs: Any) -> V1JobList: ...
    def read_namespaced_job(self, name: str, namespace: str, **kwargs: Any) -> V1Job: ...
    def get_api_resources(self, **kwargs: Any) -> V1APIResourceList: ...
    def list_cron_job_for_all_namespaces(self, **kwargs: Any) -> V1CronJobList: ...
    def list_namespaced_cron_job(self, **kwargs: Any) -> V1CronJobList: ...
