from typing import Any, Callable, Dict, Iterator, Optional

class Watch:
    def __init__(self, return_type: Optional[Any] = ...) -> None: ...
    def stop(self) -> None: ...
    def stream(
        self, func: Callable, *args: Any, **kwargs: Any
    ) -> Iterator[Dict[str, Any]]: ...
