import socket

from ..client import ApiClient
from ..client.rest import RESTResponse

class WsResponse(RESTResponse): ...
class WsApiClient(ApiClient): ...

class PortForward:
    def conected(self) -> bool: ...
    def socket(self, port_number: int) -> socket.socket: ...
    def error(self, port_number: int) -> str: ...
    def close(self) -> None: ...
